### ISSUE TITLE
 'NoneType' object has no attribute 'player_name'

### ISSUE THREAD

**Issue by OStubbs** [osu-anticheat/osu-anticheat#29]
When running:
`python anticheat.py -u 13164862 -m 983680 -n 100`

Recieved this traceback after requesting all the replays:

`Traceback (most recent call last):
  File "anticheat.py", line 113, in <module>
    anticheat.run()
  File "anticheat.py", line 50, in run
    self._run_map()
  File "anticheat.py", line 101, in _run_map
    comparer.compare(mode="double")
  File "C:\Users\Stubbs\osu-anticheat\osu-ac\comparer.py", line 92, in compare
    if(self.check_names(replay1.player_name, replay2.player_name)):
AttributeError: 'NoneType' object has no attribute 'player_name'`

**Comment by tybug** [comment]
A user with that id doesn't exist. Can you confirm you didn't mistype the command?

**Comment by OStubbs** [comment]
> 
> 
> A user with that id doesn't exist. Can you confirm you didn't mistype the command?

User got banned around 30 minutes after this.
![image](https://user-images.githubusercontent.com/45260598/52145901-2d463a00-265a-11e9-8593-15cf87e1ef72.png)

**Comment by tybug** [comment]
Unfortunate. Even if the user got banned mid download, that shouldn't account for this error. If you can replicate the error with another command that would be appreciated.
